### ISSUE TITLE
ps-remote-play is outdated

### ISSUE THREAD

**Issue by tunisiano187** [MANICX100/chocolatey#31]
Hello,
ps-remote-play is outdated, can you update it ? 

Thank you.

**Comment by brogers5** [comment]
Per https://github.com/MANICX100/chocolatey/pull/32, I will be taking over maintenance for this package.

Future issues/PRs should be opened against [brogers5/chocolatey-package-ps-remote-play](https://github.com/brogers5/chocolatey-package-ps-remote-play) instead. I will be working through the package handover process soon.

Issue can be closed, as I do not expect any further significant changes in this repo.

**Comment by brogers5** [comment]
v7.5.0.08061 has been packaged and is currently awaiting moderator approval:

https://community.chocolatey.org/packages/ps-remote-play/7.5.0.8061
